name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    name: Verify Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js >=23.10.0
        uses: actions/setup-node@v4
        with:
          node-version: '>=23.10.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: verify

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js >=23.10.0
        uses: actions/setup-node@v4
        with:
          node-version: '>=23.10.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build